### ISSUE TITLE
Upload pdf.js-seamonkey to the Pale Moon Add-ons Site

### ISSUE THREAD

**Issue by Attronarch** [IsaacSchemm/pdf.js-seamonkey#15]
Since pdf.js-seamonkey works with Pale Moon as-is, would you consider uploading it to the Pale Moon Add-ons Site?

You can do so via the Phoebus panel: https://addons.palemoon.org/panel/

**Comment by OmegaPaladin** [comment]
You can also request that pdf.js-seamonkey be added as an external add-on.  https://forum.palemoon.org/viewtopic.php?f=46&t=26759

**Comment by IsaacSchemm** [comment]
I'll see what I can do. I've uploaded add-ons for Pale Moon before, but it's been a couple years at least so I'll have to check and see what the current process is.

**Comment by epman100** [comment]
also you need to be aware of the recent changes of addons support in Palemoon version 29.2.0 and greater from [this palemoon forum page](https://forum.palemoon.org/viewtopic.php?f=1&t=26657).

verify with the makers of the Palemoon browser that the current version of pdf.js-seamonkey is compatible with the newest version of Palemoon

**Comment by Attronarch** [comment]
Thank you for uploading it @IsaacSchemm!

For those coming later, here is the link to APMO: https://addons.palemoon.org/addon/pdf-js-for-seamonkey/
